# used to work around !lambda substitution limitations 

defaults:
  icon: mdi:speedometer-medium
  
  requires:
    ident: 3
    min:
    max:
    step: 1
  first: false
  last: false
  lambda_fudge:
    inc: !lambda return x + ${step};
    dec: !lambda return x - ${step};
    recheck_threashold: !lambda id(${fan}_auto_thresh_${ident}).publish_state( id(${temp_sensor}).state >= x );
    less_than: !lambda return x <= id(${fan}_auto_${ident-1}).state;
    greater_than: !lambda return x >= id(${fan}_auto_${ident+1}).state;
    number:
      actions:
        - lambda: !lambda id(${fan}_auto_thresh_${ident}).publish_state( id(${temp_sensor}).state >= x ); 
        - if:
          condition:
            lambda: !lambda return x <= id(${fan}_auto_${ident-1}).state;
          then:
            number.set:
              id: "${fan}_auto_${ident-1}"
              "value": !lambda return x - ${step};
        - if:
            condition:
              lambda: !lambda return x >= id(${fan}_auto_${ident+1}).state;
            then:
              number.set:
                id: "${fan}_auto_${ident+1}"
                "value": !lambda return x + ${step};



  number_id: "{0}_auto_{1}"

binary_sensor:
  - id: ${fan}_auto_thresh_${ident}
    platform: analog_threshold
    sensor_id: ${temp_sensor}
    threshold: !lambda return id(${fan}_auto_${ident}).state;

number:
  - platform: template
    restore_value: true
    entity_category: config
    min_value: ${min}
    max_value: ${max}
    step: ${step}
    device_class: TEMPERATURE
    unit_of_measurement: °C
    optimistic: true
    mode: box
    id: ${fan}_auto_${ident}
    name: Auto Speed ${ident} Temperature
    initial_value: ${default}
#    icon: ${icon}
    set_action: |-
      <% if first %>
        <% set r = [number.actions[0], number.actions[ -1]] %>
      <% elif last %>
        <% set r = number.actions[:2]%>
      <%else%>
        <% set r = number.actions%>
      <% endif %>
      ${r}
      
#      <% set actions = [{"lambda": lambda_fudge.recheck_threashold}] %>
#      <% if not first %>
#        <%
#          set actions = actions+ [
#            {
#              "if": {
#                "condition": {"lambda": lambda_fudge.less_than},
#                "then": {
#                  "number.set": {
#                    "id": number_id.format(fan,ident-1),
#                    "value": lambda_fudge.dec
#                  }
#                }
#              }
#            }
#          ]
#        %>
#      <% endif %>
#      <% if not last %>
#        <%
#          set actions = actions+ [
#            {
#              "if": {
#                "condition": {"lambda": lambda_fudge.greater_than},
#                "then": {
#                  "number.set": {
#                    "id": number_id.format(fan,ident+1),
#                    "value": lambda_fudge.inc
#                  }
#                }
#              }
#            }
#          ]
#        %>
#      <% endif %>
#      ${actions}

