# used to work around !lambda substitution limitations 

defaults:
  icon: mdi:speedometer-medium
  
  requires:
    ident: 3
    min:
    max:
    step: 1
  first: false
  last: false
  lambda_fudge:
    number:
      actions:
        - lambda: !lambda id(${fan}_auto_thresh_${ident}).publish_state( id(${temp_sensor}).state >= x ); 
        - if:
            condition:
              lambda: !lambda return x <= id(${fan}_auto_${ident-1}).state;
            then:
              number.set:
                id: "${fan}_auto_${ident-1}"
                "value": !lambda return x - ${step};
        - if:
            condition:
              lambda: !lambda return x >= id(${fan}_auto_${ident+1}).state;
            then:
              number.set:
                id: "${fan}_auto_${ident+1}"
                "value": !lambda return x + ${step};

binary_sensor:
  - id: ${fan}_auto_thresh_${ident}
    platform: analog_threshold
    sensor_id: ${temp_sensor}
    threshold: !lambda return id(${fan}_auto_${ident}).state;

number:
  - platform: template
    restore_value: true
    entity_category: config
    min_value: ${min}
    max_value: ${max}
    step: ${step}
    device_class: TEMPERATURE
    unit_of_measurement: °C
    optimistic: true
    mode: box
    id: ${fan}_auto_${ident}
    name: Auto Speed ${ident} Temperature
    initial_value: ${default}
#    icon: ${icon}
    set_action: 
      then: 
        - lambda: !lambda id(${fan}_auto_thresh_${ident}).publish_state( id(${temp_sensor}).state >= x ); 

        
packages:
  number_lambdas:
    url: https://github.com/thecrisb/esp_home_configs
    files: |-
      <% set package = namespace(extends=[])%>
      <% if not first% >
        <% set package.extends = package.extends + [
            {
              "path": "projects/fan/addons/auto_speed/number_lamda.yml",
              "vars": {
                "min": true,
                "ident": ident
              }
            }
          ] 
        %>
      <% endif %>
      <% if not last% >
        <% set package.extends = package.extends + [
            {
              "path": "projects/fan/addons/auto_speed/number_lamda.yml",
              "vars": {
                "min": false,
                "ident": ident
              }
            }
          ] 
        %>
      <% endif %>
      ${package.extends}
